作業

題目:<br>
1.將下列陣列(array1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")<br>
2.呈上題的array，找出被6除餘1的數的索引<br>

In [1]:
import numpy as np

In [2]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))
reshape_array = array1.reshape(5,6,order="F")
print(reshape_array)

[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


In [6]:
#2.呈上題的array，找出被6除餘1的數的索引
#答案 : [0,5],[1,0],[2,1],[3,2],[4,3]
loc=np.where(reshape_array%6==1)
print("axis0 = ",loc[0])
print("axis1 = ",loc[1])


axis0 =  [0 1 2 3 4]
axis1 =  [5 0 1 2 3]
