作業

題目:<br>
array1 = np.array([[10, 8], [3, 5]]) <br>
1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
2. 運用上列array計算特徵值、特徵向量?
3. 運用上列array計算SVD?

In [1]:
import numpy as np

In [18]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
#取整數之後是單位矩陣
array1 = np.array([[10, 8], [3, 5]])
array1_inv = np.linalg.inv(array1)
print("Inverse of array1 = ")
print(array1_inv)
print()
print("array1 * array1_inv = ")
product_round=np.round(np.dot(array1,array1_inv))
print(product_round.astype(int))

Inverse of array1 = 
[[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]

array1 * array1_inv = 
[[1 0]
 [0 1]]


In [19]:
#2. 運用上列array計算特徵值、特徵向量?
w, v = np.linalg.eig(array1)
print("eigenvalues =")
print(w)
print("eigenvactors =")
print(v)

eigenvalues =
[13.  2.]
eigenvactors =
[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [21]:
#3. 運用上列array計算SVD?
u,s,vh=np.linalg.svd(array1)
print("u = ")
print(u)
print()
print("s = ")
print(s)
print()
print("vh = ")
print(vh)
print()

u = 
[[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]]

s = 
[13.94721714  1.86417116]

vh = 
[[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]

